const COUNTRY = {
    "Argentinian": "AR",
    "Argentina": "AR",
    "Argentine": "AR",
    "American": "US",
    "Austrian": "AT",
    "Austria": "AT",
    "Australian": "AU",
    "Australia": "AU",
    "Azerbaijan": "AZ",
    "Bahrain": "BH",
    "Belgian": "BE",
    "Belgium": "BE",
    "Brazil": "BR",
    "Brazilian": "BR",
    "British": "GB",
    "Canada": "CA",
    "Canadian": "CA",
    "Chinese": "CN",
    "China": "CN",
    "Colombian": "CO",
    "Danish": "DK",
    "Dutch": "NL",
    "Finland": "FI",
    "Finnish": "FI",
    "French": "FR",
    "France": "FR",
    "German": "DE",
    "Germany": "DE",
    "Hungary": "HU",
    "Indian": "IN",
    "Italian": "IT",
    "Italy": "IT",
    "Japanese": "JP",
    "Japan": "JP",
    "Malaysian": "MY",
    "Mexico": "MX",
    "Mexican": "MX",
    "Monaco": "MC",
    "Monegasque": "MC",
    "Netherlands": "NL",
    "New Zealander": "NZ",
    "Polish": "PL",
    "Portugal": "PT",
    "Portuguese": "PT",
    "Qatar": "QA",
    "Russian": "RU",
    "Russia": "RU",
    "Saudi Arabia": "SA",
    "Singapore": "SG",
    "Spanish": "ES",
    "Spain": "ES",
    "South African": "ZA",
    "Swedish": "SE",
    "Switzerland": "CH",
    "Swiss": "CH",
    "Thai": "TH",
    "Turkey": "TR",
    "United States": "US",
    "USA": "US",
    "UAE": "AE",
    "UK": "GB",
    "New Zealand": "NZ",
    "Finland": "FI",
};
/*


const COUNTRY={
    "British" : "gb",
    "Austrian": "at",
    "Italian": "it",
    "German": "de",
    "American": "us",
    "French": "fr",
    "Swiss": "ch",
    "Dutch": "nl",
    "Monegasque": "mc",
    "Spanish": "es",
    "Mexican": "mx",
    "Canadian":"ca",
    "Japanese": "jp",
    "Thai": "th",
    "Australian":"au",
    "Danish":"dk",
    "Argentinian":"ar",
    "New Zealander":"nz",
    "Chinese": "cn",
    "Finnish": "fi",
    "USA": "US",
    "Singapore": "SG",
    "Azerbaijan": "AZ",
    "Italy": "IT",
    "Netherlands": "NL",
    "Belgium": "BE",
    "Hungary": "HU",
    "UK": "GB",
    "Austria": "AT",
    "Spain": "ES",
    "Canada": "CA",
    "Monaco": "MC",
    "China": "CN",
    "Japan": "JP",
    "Australia": "AU",
    "Saudi Arabia": "SA",
    "Bahrain": "BH",
    "Mexico": "MX",
    "Brazil": "BR",
    "United States": "US",
    "Qatar": "QA",
    "UAE": "AE",
    "Argentine" : "AR",
    "Belgian": "BE",
    "France": "FR",
    "Germany": "DE",
    "Switzerland": "CH",
    "Russian": "RU",
    "Brazilian": "BR",
    "Polish": "PL",
    "Indian": "IN",
    "Swedish": "SE",
    "Colombian": "CO",
    "Portuguese": "PT",
    "Turkey": "TR",
    "Malaysia": "MY",
    "Argentina": "AR",
    "Portugal": "PT",
};
*/
